[package]
name = "wraithlibrary"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.0", default-features = false }
bevy_tweening = "0.8.0"

[features]
client = []
server = []
